import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'antd/dist/antd.css'
import { Input, List, Avatar, Modal } from 'antd';
import { AudioOutlined, SearchOutlined, PlusOutlined } from '@ant-design/icons';
import React, { useState } from 'react';
import Dialog from './components/dialog'

const data = [
  {
    title: '百度一下，你就知道',
    img: 'chrome://favicon2/?size=24&scale_factor=1x&show_fallback_monogram=&page_url=http%3A%2F%2Fwww.baidu.com%2F',
    href: 'https://www.baidu.com',
    key: 0
  },
  {
    title: '已购课程',
    img: '',
    href: 'https://edu.lagou.com',
    key: 1
  },
  {
    title: '百度一下，你就知道',
    img: 'chrome://favicon2/?size=24&scale_factor=1x&show_fallback_monogram=&page_url=http%3A%2F%2Fwww.baidu.com%2F',
    href: 'https://www.baidu.com',
    key: 0
  },
  {
    title: '已购课程',
    img: '',
    href: 'https://edu.lagou.com',
    key: 1
  }
];

export default function Home() {
  const [isModalVisible, setIsModalVisible] = useState(false);
  const showModal = () => {
    setIsModalVisible(true);
  };
  const handleOk = () => {
    setIsModalVisible(false);
  };

  const handleCancel = () => {
    setIsModalVisible(false);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>新标签页</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src="/logo.png" alt="Logo" width={272} height={92} />
        <Input size="large" placeholder="large size" prefix={<SearchOutlined />} suffix={<AudioOutlined />} />
        <div className={styles.flexBom}>
          {data.map(item => (
            <div key={item.key} className={styles.liBox}>
              <a href={item.href}>
                <img src={item.img} className={styles.IMG} />
                <p className={styles.boxP} title={item.title}>
                  {item.title}
                </p>
              </a>
            </div>
          ))}
          <div className={styles.liBox} onClick={showModal}>
            <PlusOutlined className={styles.IMG} />
            <p className={styles.boxP} title='添加快捷方式'>
              添加快捷方式
            </p>
          </div>
        </div>
      </main>

      <Modal title="添加快捷方式" visible={isModalVisible} onOk={handleOk} onCancel={handleCancel}>
        <Dialog></Dialog>
      </Modal>
    </div>
  )
}
